version: '3'
  
services:
    dbinit:
        build: .
        image: neo4j-twittertools
        command: bash -c "python cypher_db_init.py"
        logging:
         driver: "json-file"
         options:
          max-size: "2m"
          max-file: "2"
        volumes:
            - .env:/features/config/.env

