version: '3'
  
services:
    followingcheck_client_batch1_1:
        build: .
        image: neo4j-twittertools
        command: bash -c "python following_fetcher.py"
        logging:
         driver: "json-file"
         options:
          max-size: "2m"
          max-file: "2"
        volumes:
            - .env_followingcheck_client_b1_1:/features/config/.env
    followingcheck_client_batch1_2:
        build: .
        image: neo4j-twittertools
        command: bash -c "python following_fetcher.py"
        logging:
         driver: "json-file"
         options:
          max-size: "2m"
          max-file: "2"
        volumes:
            - .env_followingcheck_client_b1_2:/features/config/.env